### PR TITLE
fix: equate ordering of review items on review and overview pages

### LINKED ISSUE #1913: Review Status Mixed Up
### Discussed in https://github.com/pubpub/pubpub/discussions/1906

<div type='discussions-op-text'>

<sup>Originally posted by **writingpoli** March 27, 2022</sup>
So, looking at a review page for a Pub, it's saying the opposite of the actual status for each review (or just taking me to the wrong review on click):

image

When I click R4, it takes me to R1: 

image

Ideas?</div>

### PR DESCRIPTION
**Pull request by 3mcd**
Closes #1913

A quick PR that matches the ordering of the reviews on a Pub's Overview dashboard page to the order on the Reviews page (time descending).

### CODE REVIEW

File: client/containers/DashboardOverview/PubOverview/PubOverview.tsx [hunk 1]
```diff
@@ -2,19 +2,20 @@ import React from 'react';
...
-import { ContributorsList, DashboardFrame, PubHeaderBackground } from 'components';
 
 import { getAllPubContributors } from 'utils/contributors';
 import PubTimeline from './PubTimeline';
 
 require('./pubOverview.scss');
 
 type Props = {
-	pubData: any;
+	pubData: DefinitelyHas<PubPageData, 'reviews'>;
```
Comment (idreyn) [inline client/containers/DashboardOverview/PubOverview/PubOverview.tsx:18]: The `PubPageData` type is mostly (exclusively?) used on the Pub document page, and that's not what we're getting here. It's like a `SanitizedPubData` with some extra citation bits...you could reference that type here if you move it out of `server/`, or you could just define a new one inline here.

File: client/containers/DashboardOverview/PubOverview/PubOverview.tsx [hunk 2]
```diff
@@ -58,8 +59,8 @@ const PubOverview = (props: Props) => {
 				{pubData.collectionPubs.map((cp, index) => {
 					return (
 						<span key={cp.id}>
-							<a href={`/dash/collection/${cp.collection.slug}`}>
-								{cp.collection.title}
+							<a href={`/dash/collection/${cp.collection!.slug}`}>
```
Comment (idreyn) [inline client/containers/DashboardOverview/PubOverview/PubOverview.tsx:62]: We should use `getDashUrl({ collectionSlug })` here.

File: client/containers/DashboardOverview/PubOverview/PubOverview.tsx [hunk 3]
```diff
@@ -75,7 +76,7 @@ const PubOverview = (props: Props) => {
 				<div className="section-header">Reviews</div>
 				<Menu className="list-content">
 					{pubData.reviews
-						.sort((a, b) => a.createdAt - b.createdAt)
```
Comment (idreyn) [inline client/containers/DashboardOverview/PubOverview/PubOverview.tsx:78]: Oops! 😅

**Review by idreyn — APPROVED** [review]
Mostly LGTM, you definitely want to not use `PubPageData` here, but otherwise don't want to block ya
