### PR TITLE
fix: always update search results after user stops typing

### LINKED ISSUE #819: Search hangs until additional text is entered
Mentioned in #pubpub-team:

> _Weird search behavior. I've noticed that when I'm searching for a pub on the notes site, I type in some keywords and the search just spins, but when I hit backspace to try to think of another set of keywords, then the results appear below. Anyone else experiencing this?_

**Who reported this? (If not you)** Heather

### PR DESCRIPTION
**Pull request by 3mcd**
This PR resolves #819. A search will now execute at the tail end of user input into the search text box.

### CODE REVIEW

File: utils/hooks.js [hunk 1]
```diff
@@ -14,3 +15,11 @@ export const usePageContext = (previewContextObject) => {
 export const usePendingChanges = () => {
 	return useContext(PendingChanges);
 };
+
+export const useCallbackThrottled = (fn, timeout, throttleOptions, deps = []) => 
+	useCallback(throttle(fn, timeout, throttleOptions), deps);
+
+export const useEffectThrottled = (fn, timeout, throttleOptions, args = []) => {
+	const execute = useCallbackThrottled(fn, 1000, throttleOptions);
```
Comment (idreyn) [inline utils/hooks.js:23]: My guess is that you meant to eventually forward `timeout` instead of `1000` into `useCallbackThrottled`?

Comment (3mcd) [reply utils/hooks.js:23]: Yep good catch!
