### PR TITLE
fix: connection creation to external URL

### LINKED ISSUE #2646: bug: adding a connection
### What went wrong, step-by-step?
I experienced this: As I tried to add a connection external url [scholarlykitchen.sspnet.org/2023/04/19/guest-post-mapping-open-science-resources-from-around-the-world-by-discipline/](http://scholarlykitchen.sspnet.org/2023/04/19/guest-post-mapping-open-science-resources-from-around-the-world-by-discipline/) to https://access2perspectives.pubpub.org/dash/pub/uwl451tj/connections - the issue seems to be with the http:// prompt, as the page then flips away to a blank page of the same url.

### What did you expect to happen?
adding a connection

### What browser/operating system were you using?
Firefox

### PR DESCRIPTION
**Pull request by 3mcd**
## Issue(s) Resolved

Resolves #2646

## Test Plan

Create a connection with an external (non-PubPub) URL.

### CODE REVIEW

File: server/pubEdgeProposal/queries.ts [hunk 1]
```diff
@@ -94,7 +94,13 @@ export const createExternalPublicationFromMicrodata = ($) => {
 };
 
 export const createPubEdgeProposalFromArbitraryUrl = async (url) => {
-	const response = await fetch(url);
+	let response: Response;
```
Comment (qweliant) [inline server/pubEdgeProposal/queries.ts:97]: im assuming this a best practice addition

**Review by qweliant — APPROVED** [review]
