### PR TITLE
fix: use pandoc tmp file output instead of reading from stdout

### LINKED ISSUE #1943: Cannot open exported docx or epub

### PR DESCRIPTION
**Pull request by 3mcd**
Resolves #1943

Test Plan
1. Create a Pub. Add a structured citation and an unstructured citation.
2. Download the Pub as a Word document.
3. Open the file using a word processor like Pages (mac)/Word
4. Repeat steps 2-3 for epub, open with an epub viewer like Books (mac).
5. Repeat steps 2-3 for a text format like markdown and an XML format like JATS.
6. The JATS export should have one `mixed-citation` and one `element-citation`.

### CODE REVIEW

File: workers/tasks/export/notes.ts [hunk 1]
```diff
@@ -127,42 +127,35 @@ const emptyElementCitation =
...
-	return documentContent;
+						};
+					},
+				},
+			});
+			const content = `<mixed-citation>${unstructuredContentAsJats}</mixed-citation>`;
+			return `<ref id="ref-${id}">${spaceBefore}${content}${spaceAfter}</ref>`;
+		}
+		return match;
+	});
```
Comment (3mcd) [inline workers/tasks/export/notes.ts:160]: This massive diff was just me removing the `if (target === "jats_archiving")` condition.

File: workers/tasks/export/pandoc.ts [hunk 2]
```diff
@@ -186,21 +184,31 @@ export const exportWithPandoc = async (options: ExportWithPandocOptions) => {
...
+	// At this point, pandoc has written the document to our temp file. Here
+	// we do some additional post-processing.
+	if (pandocTarget === 'jats_archiving') {
+		const pandocOutput = fs.readFileSync(tmpFile.path).toString();
+		const transformedOutput = modifyJatsContentToIncludeUnstructuredNotes(
+			pandocOutput,
+			pandocNotes,
+		);
+		fs.writeFileSync(tmpFile.path, transformedOutput);
+	}
```
Comment (3mcd) [inline workers/tasks/export/pandoc.ts:213]: I moved the check here because overwriting the contents of docx/epub files was corrupting the contents too (even when it should have been a no-op). Still not totally sure why.

File: workers/tasks/export/notes.ts [hunk 3]
```diff
@@ -127,42 +127,35 @@ const emptyElementCitation =
 
 export const modifyJatsContentToIncludeUnstructuredNotes = (
 	documentContent: string,
-	target: PandocTarget,
```
Comment (qweliant) [inline workers/tasks/export/notes.ts:130]: Remove unused export `PandocTarget`

**Review by qweliant — APPROVED** [review]
