### PR TITLE
fix: use the latest formatted PDF or export in metadata

### LINKED ISSUE #923: Citation_pdf_url linking to old featured pdf
I probably got something wrong when I added the `citation_` tags way back when.

**What went wrong, step-by-step?**
1. Visit https://jtrialerror.pubpub.org/pub/alcoholcues/release/1
1. Download the PDF from the download button, get this fancy PDF: https://assets.pubpub.org/qr3ldf5z/61594913360554.pdf
1. But, when you view source and look at the `citation_pdf_url` meta field, it links here, to an old version: https://assets.pubpub.org/vpox2noi/51594136813036.pdf
...

**What did you expect to happen?**
The citation_pdf_url field should always link to the current featured PDF export

**What URL can we use to see the issue?**
https://jtrialerror.pubpub.org/pub/alcoholcues/release/1

**What browser/operating system were you using?**

---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**
Thomas Jorna
https://knowledgefutures.freshdesk.com/a/tickets/1557

### PR DESCRIPTION
**Pull request by gabestein**
Sorry, one more! Resolves #923 by ordering downloads by date and exports by historyKey.

### CODE REVIEW

File: utils/pub/metadata.js [hunk 1]
```diff
@@ -1,12 +1,17 @@
 export const getPDFDownload = (pub) => {
 	const downloads = pub.downloads;
 	const exports = pub.activeBranch.exports;
+	// console.log(exports);
```
Comment (3mcd) [inline utils/pub/metadata.js:4]: Some commented code snuck in here.

Comment (gabestein) [reply utils/pub/metadata.js:4]: Sigh, moving too fast today.

**Comment by gabestein** [comment]
Much obliged!
