### PR TITLE
Fix discussion email sending

### LINKED ISSUE #3035: Discussion reply and digest emails not sending
### What went wrong, step-by-step?

1. Make sure your email settings are set to receive replies to comments in your preferences: https://www.pubpub.org/legal/settings
2. Create a new pub
3. From another account, add a discussion to that pub
4. Notice that no email is sent, and no attempts show up in mailgun logs

It appears that emails may have stopped for both in August 2023!

### What did you expect to happen?
Email notification of discussion is sent.

### What URL can we use to see the issue?
https://notes.knowledgefutures.org/pub/jph8ooz1/draft

## Optional
Repeat for activity digests (make sure subscribe is turned on in e.g. https://notes.knowledgefutures.org/dash/activity)

### PR DESCRIPTION
**Pull request by kalilsn**
Discussion emails are sent by an `afterCreate` hook on `UserNotification` creation. However, these hooks don't run by default on bulk methods like `UserNotification.bulkCreate`.

https://sequelize.org/docs/v6/other-topics/hooks/#model-hooks:
>Note: methods like bulkCreate do not emit individual hooks by default - only the bulk hooks. However, if you want individual hooks to be emitted as well, you can pass the { individualHooks: true } option to the query call. However, this can drastically impact performance, depending on the number of records involved (since, among other things, all instances will be loaded into memory).

## Issue(s) Resolved
Resolves #3035

## Test Plan
Create a pub, comment on it, then reply from another account. You should receive an email.

### Notes/Context/Gotchas
~I'm not quite sure how this ever worked, since it doesn't seem like sequelize changed the bulkCreate api recently (this behavior is in the v5 docs too).~ I see now that this was deleted in https://github.com/pubpub/pubpub/pull/2960/commits/06f99929a2b231d417eb3387f3019ca047e3cb15 hopefully just by mistake, though let me know if that's wrong and this is breaking something else.

I'm not sure how the activityDigest email script gets run, but if those aren't being sent it seems like a separate issue since they don't use hooks.

### CODE REVIEW

**Comment by tefkah** [comment]
I can confirm that I got emails both from people adding comments to the Pub and from replying to a discussion I started!

File: server/userNotification/create.ts [hunk 1]
```diff
@@ -93,6 +93,7 @@ const createNotificationsForThreadComment = async (
 				activityItemId: item.id,
 			};
 		}),
+		{ individualHooks: true },
```
Comment (tefkah) [inline server/userNotification/create.ts:96]: I'm _pretty_ sure I removed this by mistake. I came across this bug/"feature" in other places as well, I remember adding this somewhere, but don't think I ever intentionally removed it. Very sorry!

**Comment by tefkah** [comment]
I added a test to make sure the emails are sent correctly.
Normally I would just ask for the test to be added, but since mocking and checking if something has been called is a bit tricky in v6 and I happened to have done that before, I just added it myself real quick! (also I was the one that broke it and want to make sure i did not break it again 😅)

**Review by tefkah — APPROVED** [review]

File: server/userNotification/create.ts (hunk 1 above)
Comment (kalilsn) [reply server/userNotification/create.ts:96]: not a problem! thanks for adding the test!
