### PR TITLE
fix: extra height on sticky banner in Pub release view

### LINKED ISSUE #1952: Pub sticky header too long in some cases
So we keep track of it for next week...

### What went wrong, step-by-step?
1. Scroll down on a pub, see the sticky header is too long

### What did you expect to happen?
Sticky header is the length of line of text only.

### What URL can we use to see the issue?
https://notes.knowledgefutures.org/pub/9p4jxiws/release/1

### What browser/operating system were you using?
OS X Latest / Chrome Latest

===

### Have any screenshots? (Attach them by dragging the image here)
Screen Shot 2022-04-14 at 16 36 42

### PR DESCRIPTION
**Pull request by 3mcd**
Resolves #1952

Test Plan
1. Load a Pub release
2. Scroll the page so the sticky banner appears and sticks to the top of the viewport.
3. The banner should not have extra "padding" at the top.

### CODE REVIEW

File: client/containers/Pub/PubHeader/ResponsiveHeaderButton.tsx [hunk 1]
```diff
@@ -17,13 +17,9 @@ const ResponsiveHeaderButton = React.forwardRef((props: Props, ref) => {
...
 	const largeOnlyProps = { outerLabel, showCaret };
 	const smallOnlyProps = { labelPosition };
-
 	const { viewportWidth } = useViewport();
 
-	if (viewportWidth === null) {
-		return null;
-	}
-	if (viewportWidth > mobileViewportCutoff) {
+	if (viewportWidth === null || viewportWidth > mobileViewportCutoff) {
```
Comment (3mcd) [inline client/containers/Pub/PubHeader/ResponsiveHeaderButton.tsx:22]: This is the only relevant change. The width/height values returned by `useViewport` are `null` during SSR. Previously, we returned `null` from `ResponsiveHeaderButton` during SSR. With these changes, we'll render the `LargeHeaderButton` by default. On mobile, the buttons will appear large and then shrink down once the document hydrates. I've confirmed that the sticky banner works on both mobile and desktop viewport widths.

**Review by howebenhowe — APPROVED** [review]

**Comment by howebenhowe** [comment]
LGTM, tested properly for both mobile and desktop viewport widths.
