### PR TITLE
feat: add digest links; fix discussion overflow

### LINKED ISSUE #1793: Add Pub links to activity digest
- Make Pub title in digest email a link to the Pub slug link
- Resolve discussion text box overflow

### PR DESCRIPTION
**Pull request by 3mcd**
Resolves #1793

This PR
* adds links to Pub and Collection activity item titles in digest emails
* uses `colspan` to prevent discussion snippets from overflowing

*Test Steps*

* Visit http://localhost:9876/email/digest
* Verify that Pub and Collection titles are clickable and take you to the correct URL
* Verify that discussion snippets are contained within the width of the email (i.e. they do not overflow to the right).

### CODE REVIEW

File: server/utils/email/digest.tsx [hunk 1]
```diff
@@ -44,6 +45,17 @@ const getAffectedObject = (item: ActivityItem, associations: ActivityAssociation
 	};
 };
 
+const getAffectedObjectUrl = (item: ActivityItem, associations: ActivityAssociations) => {
+	const community = Object.values(associations.community)[0];
+	if (item.pubId) {
+		return pubUrl(community, associations.pub[item.pubId]);
```
Comment (idreyn) [inline server/utils/email/digest.tsx:51]: In the case where a Pub was deleted , `associations.pub[item.pubId]` will be undefined — so we gotta check for the existence of that too before calling `pubUrl()`.

File: server/utils/email/digest.tsx [hunk 2]
```diff
@@ -44,6 +45,17 @@ const getAffectedObject = (item: ActivityItem, associations: ActivityAssociation
...
+	}
+	if (item.collectionId) {
+		return collectionUrl(community, associations.collection[item.collectionId]);
```
Comment (idreyn) [inline server/utils/email/digest.tsx:54]: Here too.

File: server/utils/email/digest.tsx [hunk 3]
```diff
@@ -44,6 +45,17 @@ const getAffectedObject = (item: ActivityItem, associations: ActivityAssociation
...
+	}
+	return undefined;
```
Comment (idreyn) [inline server/utils/email/digest.tsx:56]: $0.02 — I think we should try to stick to `null` for a falsy fallback value, so `undefined` more strongly carries its built-in meanings of "this key doesn't exist" or "no return value".

**Review by idreyn — CHANGES_REQUESTED** [review]
Tested and works great, but see my comments about the `associations` object!

**Review by idreyn — APPROVED** [review]
LGTM, thanks!
